### ISSUE TITLE
Unity.Wcf does not have a strong name

### ISSUE THREAD

**Issue by AlbertBJ** [ViceIce/unity.wcf#3]
My project is a strong name assembly and it references Unity.Wcf(version 1.0.0.0)（from nuget）

But when i build this project, the error occur  " Assembly generation failed -- Referenced assembly 'Unity.Wcf' does not have a strong name"

How should i change the Unity.Wcf assembly into a strong name assembly?

Thank you very much

**Comment by viceice** [comment]
Please upgrade to Version 1.1.0 or higher.

**Comment by AlbertBJ** [comment]
Thank you very much for your reply.
   Have other options besides upgrading?

**Comment by viceice** [comment]
I dont think so. Version 1.1.0 should be fully compatible with v1.0.0 (excerpt the assembly signing).

**Comment by AlbertBJ** [comment]
thx
