### ISSUE TITLE
Unity 5

### ISSUE THREAD

**Issue by svenssj** [ViceIce/unity.wcf#8]
This needs to be updated to support unity 5.

**Comment by viceice** [comment]
Please test [Unity.Wcf](https://www.nuget.org/packages/Unity.Wcf/4.0.0-rc02) for Unity 5

**Comment by kcragin** [comment]
You can't test it against Unity 5. The namespaces have changed. You will have to update the code.

**Comment by viceice** [comment]
Have you tried the 4.0.0-rc01 build?

Am 29.11.2017 23:59 schrieb Kit Cragin <notifications@github.com>:

You can't test it against Unity 5. The namespaces have changed. You will have to update the code.

**Comment by svenssj** [comment]
The rc02 build still adds a reference to Microsoft.Practices.Unity in WcfServiceFactory.cs.

If I change that to using Unity; it compiles. 

I do not have enough time or knowledge to perform thurough runtime testing.

**Comment by viceice** [comment]
Pushed prerelease 4.0.0-rc03 to nuget
