### ISSUE TITLE
NuGet package doesn't add *ServiceFactory file

### ISSUE THREAD

**Issue by rhombuslabs** [ViceIce/unity.wcf#9]
@ViceIce 
All of the instructions I've seen so far claim that Unity.WCF will add files to my WCF project. It adds no files, even on a clean project.

I'm using Visual Studio 2017 with a .NET Framework 4.7.2 WcfService project.

**Comment by rhombuslabs** [comment]
Really, I'd be quite satisfied if the Readme was updated with current instructions on using the package. Thanks.

**Comment by viceice** [comment]
Simply add a class which extends from `UnityServiceHostFactory` and set this as `Factory` in your `svc` file.
Then override the `ConfigureContainer` method to configure your unity instance.

Regards
